/**
 * generate-platform-manifests.ts — Create package.json + postinstall.js for each platform package.
 *
 * Usage:
 *   pnpm tsx scripts/generate-platform-manifests.ts
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import config from '../publish.config';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const rootPkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
const version = rootPkg.version;

const PLATFORM_DIR = join(ROOT, 'platform-packages');

const PLATFORM_MAP: Record<string, { os: string; cpu: string; ext: string }> = {
  'darwin-arm64':  { os: 'darwin', cpu: 'arm64', ext: '' },
  'darwin-x64':    { os: 'darwin', cpu: 'x64',   ext: '' },
  'linux-x64':     { os: 'linux',  cpu: 'x64',   ext: '' },
  'windows-x64':   { os: 'win32',  cpu: 'x64',   ext: '.exe' },
};

function generatePostinstall(): string {
  return `#!/usr/bin/env node
/**
 * postinstall.js — Make the binary executable on Unix systems.
 * Auto-generated by generate-platform-manifests.ts
 */
const { existsSync, chmodSync } = require('fs');
const { join } = require('path');

const pkg = require('./package.json');
const binaryPath = join(__dirname, pkg.main);

if (existsSync(binaryPath)) {
  try {
    chmodSync(binaryPath, 0o755);
  } catch {
    // Ignore chmod errors on Windows
  }
}
`;
}

function main() {
  console.log(`📦 Generating platform manifests (version: ${version})`);

  for (const binary of config.binaries) {
    for (const platform of config.platforms) {
      const mapping = PLATFORM_MAP[platform];
      if (!mapping) {
        console.error(`  ❌ Unknown platform: ${platform}`);
        continue;
      }

      const pkgName = `${config.scope}/${binary.scope}-${platform}`;
      const pkgDir = join(PLATFORM_DIR, `${binary.scope}-${platform}`);
      const binaryFile = `${binary.name}${mapping.ext}`;

      if (!existsSync(pkgDir)) {
        mkdirSync(pkgDir, { recursive: true });
      }

      const manifest = {
        name: pkgName,
        version,
        description: `${binary.name} binary for ${platform}`,
        os: [mapping.os],
        cpu: [mapping.cpu],
        main: binaryFile,
        files: [binaryFile, 'postinstall.js'],
        scripts: {
          postinstall: 'node postinstall.js',
        },
        license: rootPkg.license || 'MIT',
        repository: {
          type: 'git',
          url: config.repositoryUrl,
        },
      };

      writeFileSync(join(pkgDir, 'package.json'), JSON.stringify(manifest, null, 2) + '\n');
      console.log(`  ✅ ${pkgName}`);

      writeFileSync(join(pkgDir, 'postinstall.js'), generatePostinstall());
    }
  }

  console.log(`\n📊 Generated ${config.binaries.length * config.platforms.length} platform package(s)`);
}

main();
