name: Publish (dry run)

on:
  pull_request:
    branches: [main]

concurrency:
  group: publish-dry-run-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-dry-run:
    name: Publish (dry run)
    needs: []
    uses: ./.github/workflows/release.yml
    with:
      dry_run: true
    secrets: inherit
